spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    schema: classpath:schema.sql
  application:
    name: ymir
server:
  servlet:
    context-path: /ymir
mybatis:
  mapper-locations: classpath:/sqlmap/*.xml
