INSERT INTO SYS_CODE (SYS_GROUP, SYS_NAME, SYS_VALUE, MEMO, CREATE_ID, CREATE_DATE, UPDATE_ID, UPDATE_DATE)
VALUES ('SYS', 'GIT_TOKEN', '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', '2024/4/7 expire', 'SYS', NOW(), null, null);

INSERT INTO SYS_USER (ACCOUNT, USER_NAME, EMAIL, CREATE_ID, CREATE_DATE, UPDATE_ID, UPDATE_DATE)
VALUES ('B0132', 'Tony', 'tony@gmail.com', 'SYS', NOW(), null, null);
INSERT INTO SYS_USER (ACCOUNT, USER_NAME, EMAIL, CREATE_ID, CREATE_DATE, UPDATE_ID, UPDATE_DATE)
VALUES ('A9090', 'Liz', 'liz@gmail.com', 'SYS', NOW(), null, null);
INSERT INTO SYS_USER (ACCOUNT, USER_NAME, EMAIL, CREATE_ID, CREATE_DATE, UPDATE_ID, UPDATE_DATE)
VALUES ('A8703', 'Nick', 'nick@gmail.com', 'SYS', NOW(), null, null);
INSERT INTO SYS_USER (ACCOUNT, USER_NAME, EMAIL, CREATE_ID, CREATE_DATE, UPDATE_ID, UPDATE_DATE)
VALUES ('A8672', 'Ruby', 'ruby@gmail.com', 'SYS', NOW(), null, null);